### ISSUE TITLE
JournalLine.contactRef

### ISSUE THREAD

**Issue by Bo0mer** [codatio/client-sdk-go#442]
Hello,

I'm browsing through your [swagger API definition](https://api.codat.io/swagger/v1/swagger.json) and can see that the JournalLine object has a `contactRef` field:

```text
      "Codat.DataContracts.Datasets.JournalLine": {
        "required": [
          "netAmount"
        ],
        "type": "object",
        "properties": {
          "description": {
            "type": "string",
            "nullable": true
          },
          "netAmount": {
            "type": "number",
            "format": "double"
          },
          "currency": {
            "type": "string",
            "nullable": true
          },
          "accountRef": {
            "$ref": "#/components/schemas/Codat.DataContracts.Datasets.AccountRef"
          },
          "tracking": {
            "$ref": "#/components/schemas/Codat.DataContracts.Datasets.Tracking"
          },
          "contactRef": {
            "$ref": "#/components/schemas/Codat.DataContracts.Datasets.ContactRef"
          }
        },
        "additionalProperties": false
      },
```

However, I'm not able to find information about what that field holds. I'm trying to get information about the supplier or customer that is referenced from the bill or invoice that produced this journal line.

Also, when calling the API the field does not seem to be populated. I'm testing with Xero integration using Xero's 'Demo Company' that they provide out of the box.

So, the questions here are:
* would (and when) the `contactRef` would be supported by the API, respectively this package?
* what information will it hold -- would it be direct link to a supplier or customer, or it will be something else?

Please do let me know if any more details are necessary.

Thanks,
Ivan

**Comment by dcoplowe** [comment]
Hi Ivan, 

I'd recommend looking at our official [OAS in GitHub](https://github.com/codatio/oas) or our [API ref](https://docs.codat.io/using-the-api/overview) for more context on our endpoints and schema definitions. With regards to the `contactRef` it looks like its currently missing from our documentation. I've created a ticket for this and will let you know once we've update our docs. In the meantime the `contactRef` schema is defined below

```yaml
contactRef:
   type: object
   properties:
      id: 
          type: string
          description: Unique identifier for the contact.
      dataType:
          type: string
          description: The data type the ID can be accessed from either a Supplier or Customer.
```
